name: escala_game
description: A Flutter app for the Escala game.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1          # Para solicitudes HTTP a la API
  web_socket_channel: ^3.0.1  # Para WebSocket
  shared_preferences: ^2.2.0
  provider: ^6.1.2      # Para manejo de estado
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
